### ISSUE TITLE
建议Win版选择自定义播放器不要选择目录，而是选择可执行文件

### ISSUE THREAD

**Issue by hhun** [qq528/snail#2]
建议Win版选择自定义播放器不要选择目录，而是选择可执行文件
例如：`MPV-EASY Player`的启动文件是`MPV-EASY Player.exe`而不是`mpv.exe`

`MPV-EASY Player`更好用，有可视化菜单，可以支持杜比视界。
在`MPV-EASY Player`里面把`MPV-EASY Player.exe`重命名为`mpv.exe`也没有用。

# 希望蜗牛能兼容 `MPV-EASY Player`

**Comment by qq528** [comment]
最新版已实现
