### ISSUE TITLE
建议PC版支持`MPV-EASY Player`，MPV-EASY Player是带有可视化界面的MPV播放器

### ISSUE THREAD

**Issue by hhun** [qq528/snail#8]
@qq528 
建议PC版支持`MPV-EASY Player`，MPV-EASY Player是带有**可视化界面**的MPV播放器
PC内置的MPV播放器没有可视化界面，用起来不方便

现在的蜗牛云盘选择MPV-EASY Player后，能正常播放，但是不支持拖动进度条。
![MPV-EASY Player](https://github.com/qq528/snail/assets/19625243/f2e4e682-99b1-4f7f-a784-db9da2243a2f)

**Comment by qq528** [comment]
最新版已对内嵌mpv进行了优化，增加了常规界面可视化操作。
<img width="896" alt="image" src="https://github.com/qq528/snail/assets/13740709/e2a09ded-79bd-4c84-9654-13f34e37b396">
